# Generated by Django 5.0 on 2023-12-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profileing',
            new_name='profileimg',
        ),
    ]
